In [1]:
import pandas as pd
from glob import glob
import os
import numpy as np

In [2]:
root = 'data'
files = glob(os.path.join(root, '**/*updated.csv'), recursive=True)
files

['data/Mar_2024/cnmfe_output_updated.csv',
 'data/Jan_2024/cnmfe_output_updated.csv',
 'data/May_2024/cnmfe_output_updated.csv']

In [3]:
session_file_path = 'data/updated_session_file_MiniscopeCW_all_Moises.csv'
session_file = pd.read_csv(session_file_path)
# Rename Session outcome to Session Outcome
session_file.rename(columns={'Session outcome': 'Session Outcome'}, inplace=True)
# Convert Cohort to string
session_file['Cohort'] = session_file['Cohort'].astype(str)
print(session_file['Cohort'].unique())
session_file.head()

['Oct_2021' 'Mar_2024' 'Jan_2024' 'May_2024']

,Session,Cohort,Date,Mouse,Pair,Criteria,Sex,Final Outcome,Session Outcome,DayofHelping,...,Motion Corrected Path,Bottom camera,Side camera,Miniscope video,DLCBottom,ManualAnnotationSide,USV helper,USV victim,AdaNotes,Comments
0,HBTD6,Oct_2021,29.10.2021,847,0847-5839,SSCW,M,H,H,4,...,processed-data/Oct_2021/HBTD6/cnmfe_data/memma...,Basler_acA2040-90umNIR__23659702__20211029_102...,Basler_acA2040-90umNIR__23659707__20211029_102...,2021-10-29-10-25-58_video,processed-data/Oct_2021/HBTD6/bottom_camera/al...,Basler_acA2040-90umNIR__23659707__20211029_102...,NaN,NaN,3.5,put the wire protection on was to heavy for t...
1,HBTD5,Oct_2021,28.10.2021,847,0847-5839,SSCW,M,H,H,3,...,processed-data/Oct_2021/HBTD5/cnmfe_data/memma...,Basler_acA2040-90umNIR__23659702__20211028_133...,Basler_acA2040-90umNIR__23659707__20211028_133...,2021-10-28-13-34-33_video,processed-data/Oct_2021/HBTD5/bottom_camera/al...,Basler_acA2040-90umNIR__23659707__20211028_133...,NaN,NaN,0.4,(ADA NOTE: 0.4 min)
2,Pool,Oct_2021,31.10.2021,847,0847-5839,SSCW,M,NaN,CTRL,Pool,...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,Basler_acA2040-90umNIR__23659702__20211031_132...,Basler_acA2040-90umNIR__23659707__20211031_132...,2021-10-31-12-26-49_video,processed-data/Oct_2021/Pool/bottom_camera/ali...,Basler_acA2040-90umNIR__23659707__20211031_132...,NaN,NaN,NaN,NaN
3,HBTD2,Oct_2021,24.10.2021,847,0847-5839,SSCW,M,H,NH,0,...,processed-data/Oct_2021/HBTD2/cnmfe_data/memma...,Basler_acA2040-90umNIR__23659702__20211024_152...,Basler_acA2040-90umNIR__23659707__20211024_152...,2021-10-24-15-20-12_video,processed-data/Oct_2021/HBTD2/bottom_camera/al...,Basler_acA2040-90umNIR__23659707__20211024_152...,NaN,NaN,NaN,NaN
4,Empty,Oct_2021,30.10.2021,847,0847-5839,SSCW,M,NaN,CTRL,Empty,...,processed-data/Oct_2021/Empty/cnmfe_data/memma...,Basler_acA2040-90umNIR__23659702__20211030_122...,Basler_acA2040-90umNIR__23659707__20211030_122...,2021-10-30-12-27-08_video,processed-data/Oct_2021/Empty/bottom_camera/al...,NaN,NaN,NaN,NaN,NaN

In [7]:
mar_data = pd.read_csv(files[0])
jan_data = pd.read_csv(files[1])
may_data = pd.read_csv(files[2])
oct_data = pd.read_csv(files[3])

# Add cohort to each data
jan_data['Cohort'] = 'Jan_2024'
mar_data['Cohort'] = 'Mar_2024'
may_data['Cohort'] = 'May_2024'


# Convert Cohort to str
jan_data['Cohort'] = jan_data['Cohort'].astype(str)
mar_data['Cohort'] = mar_data['Cohort'].astype(str)
may_data['Cohort'] = may_data['Cohort'].astype(str)

In [8]:
mar_data.head()

,Session,Mouse,Total Components,Num Accepted,Num Rejected,FPS,Dimensions,Correlation Image Path,Peak-to-Noise Ratio Path,CNMFE Model Path,Motion Corrected Path,Session Duration,Session Outcome,Final Outcome,Time Victim Inserted,Sex,Pair,Cohort
0,HBTD6,7964,223,54,169,30,"(400, 640)",processed-data/Mar_2024/HBTD6/cnmfe_data/corre...,processed-data/Mar_2024/HBTD6/cnmfe_data/peak_...,processed-data/Mar_2024/HBTD6/cnmfe_model/Mois...,processed-data/Mar_2024/HBTD6/cnmfe_data/memma...,202.0,H,H,62.0,F,7964-7963,Mar_2024
1,REMNvlCtx,7964,184,47,137,30,"(400, 640)",processed-data/Mar_2024/REMNvlCtx/cnmfe_data/c...,processed-data/Mar_2024/REMNvlCtx/cnmfe_data/p...,processed-data/Mar_2024/REMNvlCtx/cnmfe_model/...,processed-data/Mar_2024/REMNvlCtx/cnmfe_data/m...,242.0,H,H,67.0,F,7964-7963,Mar_2024
2,HBTD5,7964,184,45,139,30,"(400, 640)",processed-data/Mar_2024/HBTD5/cnmfe_data/corre...,processed-data/Mar_2024/HBTD5/cnmfe_data/peak_...,processed-data/Mar_2024/HBTD5/cnmfe_model/Mois...,processed-data/Mar_2024/HBTD5/cnmfe_data/memma...,197.0,H,H,62.0,F,7964-7963,Mar_2024
3,RECNvlCtx,7964,255,53,202,30,"(400, 640)",processed-data/Mar_2024/RECNvlCtx/cnmfe_data/c...,processed-data/Mar_2024/RECNvlCtx/cnmfe_data/p...,processed-data/Mar_2024/RECNvlCtx/cnmfe_model/...,processed-data/Mar_2024/RECNvlCtx/cnmfe_data/m...,200.0,H,H,63.0,F,7964-7963,Mar_2024
4,Pool,7964,238,70,168,30,"(400, 640)",processed-data/Mar_2024/Pool/cnmfe_data/correl...,processed-data/Mar_2024/Pool/cnmfe_data/peak_t...,processed-data/Mar_2024/Pool/cnmfe_model/Moise...,processed-data/Mar_2024/Pool/cnmfe_data/memmap...,NaN,Pool,H,NaN,F,7964-7963,Mar_2024

In [9]:
# Combine all data
all_output_data = pd.concat([jan_data, mar_data, may_data, oct_data], ignore_index=True)
all_output_data.head()

,Session,Mouse,Total Components,Num Accepted,Num Rejected,FPS,Dimensions,Correlation Image Path,Peak-to-Noise Ratio Path,CNMFE Model Path,Motion Corrected Path,Session Duration,Session Outcome,Final Outcome,Time Victim Inserted,Sex,Pair,Cohort
0,Hab1,8000,113,23,90,30,"(400, 640)",processed-data/Jan_2024/Hab1/cnmfe_data/correl...,processed-data/Jan_2024/Hab1/cnmfe_data/peak_t...,processed-data/Jan_2024/Hab1/cnmfe_model/2024-...,processed-data/Jan_2024/Hab1/cnmfe_data/memmap...,NaN,NaN,H,NaN,M,8000-7999,Jan_2024
1,HBTD6,8000,153,31,122,30,"(400, 640)",processed-data/Jan_2024/HBTD6/cnmfe_data/corre...,processed-data/Jan_2024/HBTD6/cnmfe_data/peak_...,processed-data/Jan_2024/HBTD6/cnmfe_model/2024...,processed-data/Jan_2024/HBTD6/cnmfe_data/memma...,243.0,H,H,68.0,M,8000-7999,Jan_2024
2,REMNvlCtx,8000,732,190,542,30,"(400, 640)",processed-data/Jan_2024/REMNvlCtx/cnmfe_data/c...,processed-data/Jan_2024/REMNvlCtx/cnmfe_data/p...,processed-data/Jan_2024/REMNvlCtx/cnmfe_model/...,processed-data/Jan_2024/REMNvlCtx/cnmfe_data/m...,143.0,H,H,64.0,M,8000-7999,Jan_2024
3,HBTD5,8000,157,35,122,30,"(400, 640)",processed-data/Jan_2024/HBTD5/cnmfe_data/corre...,processed-data/Jan_2024/HBTD5/cnmfe_data/peak_...,processed-data/Jan_2024/HBTD5/cnmfe_model/2024...,processed-data/Jan_2024/HBTD5/cnmfe_data/memma...,185.0,H,H,70.0,M,8000-7999,Jan_2024
4,RECNvlCtx,8000,413,95,318,30,"(400, 640)",processed-data/Jan_2024/RECNvlCtx/cnmfe_data/c...,processed-data/Jan_2024/RECNvlCtx/cnmfe_data/p...,processed-data/Jan_2024/RECNvlCtx/cnmfe_model/...,processed-data/Jan_2024/RECNvlCtx/cnmfe_data/m...,265.0,H,H,65.0,M,8000-7999,Jan_2024

In [13]:
# Save the updated session file, add updated to the name
session_file.to_csv(session_file_path.replace('.csv', '_updated.csv'), index=False)
print(f"Saved updated session file to {session_file_path.replace('.csv', '_updated.csv')}")

Saved updated session file to data/updated_session_file_MiniscopeCW_all_Moises_updated.csv

In [14]:
# Load the updated session file
session_file = pd.read_csv(session_file_path.replace('.csv', '_updated.csv'))
session_file.head()

,Session,Cohort,Date,Mouse,Pair,Criteria,Sex,Final Outcome,Session Outcome,DayofHelping,...,Motion Corrected Path,Bottom camera,Side camera,Miniscope video,DLCBottom,ManualAnnotationSide,USV helper,USV victim,AdaNotes,Comments
0,RECNvlCtx,Jan_2024,22.01.2024,8000,8000-7999,SSCW,M,H,H,RECNvlCtx,...,processed-data/Jan_2024/RECNvlCtx/cnmfe_data/m...,Basler_acA2040-90umNIR__bottom__20240122_8000-...,Basler_acA2040-90umNIR__side__20240122_8000-79...,2024-01-22-13-10-08_video,processed-data/Jan_2024/RECNvlCtx/bottom_camer...,Basler_acA2040-90umNIR__side__20240122_8000-79...,NaN,NaN,NaN,NaN
1,Hab1,Jan_2024,NaN,8000,8000-7999,NaN,M,H,NaN,NaN,...,processed-data/Jan_2024/Hab1/cnmfe_data/memmap...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HBTD6,Jan_2024,20.01.2024,8000,8000-7999,SSCW,M,H,H,4,...,processed-data/Jan_2024/HBTD6/cnmfe_data/memma...,Basler_acA2040-90umNIR__bottom__20240120_8000-...,Basler_acA2040-90umNIR__side__20240120_8014-80...,2024-01-20-14-37-10_video,processed-data/Jan_2024/HBTD6/bottom_camera/al...,Basler_acA2040-90umNIR__side__20240120_8000-79...,NaN,NaN,NaN,NaN
3,HBTD5,Jan_2024,19.01.2024,8000,8000-7999,SSCW,M,H,H,3,...,processed-data/Jan_2024/HBTD5/cnmfe_data/memma...,Basler_acA2040-90umNIR__bottom__20240119_8000-...,Basler_acA2040-90umNIR__side__20240119_8000-79...,2024-01-19-12-16-34_video,processed-data/Jan_2024/HBTD5/bottom_camera/al...,Basler_acA2040-90umNIR__side__20240119_8000-79...,NaN,NaN,NaN,NaN
4,Pool,Jan_2024,24.01.2024,8000,8000-7999,SSCW,M,H,CTRL,Pool,...,processed-data/Jan_2024/Pool/cnmfe_data/memmap...,Basler_acA2040-90umNIR__bottom__20240124_8000-...,Basler_acA2040-90umNIR__side__20240124_8000-79...,2024-01-24-12-04-07_video,processed-data/Jan_2024/Pool/bottom_camera/ali...,Basler_acA2040-90umNIR__side__20240124_8000-79...,NaN,NaN,NaN,NaN

In [15]:
unique_cohorts = session_file['Cohort'].unique()
unique_cohorts

array(['Jan_2024', 'Mar_2024', 'May_2024', 'Oct_2021'], dtype=object)

In [8]:
# Parse TimeVictimInsertion, TimeVictimCrossing columns from mm:ss to seconds format
# jan_data['TimeVictimInsertion'] = jan_data['TimeVictimInsertion'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
# jan_data['TimeVictimCrossing'] = jan_data['TimeVictimCrossing'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
# jan_data.head()

,Session,Mouse,Total Components,Num Accepted,Num Rejected,FPS,Dimensions,Correlation Image Path,Peak-to-Noise Ratio Path,CNMFE Model Path,Motion Corrected Path,Session Duration,Session Outcome,Final Outcome,Time Victim Inserted,Sex,Pair,Cohort
0,HBTD6,7964,223,54,169,30,"(400, 640)",processed-data/Mar_2024/HBTD6/cnmfe_data/corre...,processed-data/Mar_2024/HBTD6/cnmfe_data/peak_...,processed-data/Mar_2024/HBTD6/cnmfe_model/Mois...,processed-data/Mar_2024/HBTD6/cnmfe_data/memma...,202.0,H,H,62.0,F,7964-7963,Jan_2024
1,REMNvlCtx,7964,184,47,137,30,"(400, 640)",processed-data/Mar_2024/REMNvlCtx/cnmfe_data/c...,processed-data/Mar_2024/REMNvlCtx/cnmfe_data/p...,processed-data/Mar_2024/REMNvlCtx/cnmfe_model/...,processed-data/Mar_2024/REMNvlCtx/cnmfe_data/m...,242.0,H,H,67.0,F,7964-7963,Jan_2024
2,HBTD5,7964,184,45,139,30,"(400, 640)",processed-data/Mar_2024/HBTD5/cnmfe_data/corre...,processed-data/Mar_2024/HBTD5/cnmfe_data/peak_...,processed-data/Mar_2024/HBTD5/cnmfe_model/Mois...,processed-data/Mar_2024/HBTD5/cnmfe_data/memma...,197.0,H,H,62.0,F,7964-7963,Jan_2024
3,RECNvlCtx,7964,255,53,202,30,"(400, 640)",processed-data/Mar_2024/RECNvlCtx/cnmfe_data/c...,processed-data/Mar_2024/RECNvlCtx/cnmfe_data/p...,processed-data/Mar_2024/RECNvlCtx/cnmfe_model/...,processed-data/Mar_2024/RECNvlCtx/cnmfe_data/m...,200.0,H,H,63.0,F,7964-7963,Jan_2024
4,Pool,7964,238,70,168,30,"(400, 640)",processed-data/Mar_2024/Pool/cnmfe_data/correl...,processed-data/Mar_2024/Pool/cnmfe_data/peak_t...,processed-data/Mar_2024/Pool/cnmfe_model/Moise...,processed-data/Mar_2024/Pool/cnmfe_data/memmap...,NaN,Pool,H,NaN,F,7964-7963,Jan_2024

In [11]:
print(len(session_file['Pair'].unique()), len(all_output_data['Pair'].unique()))

19 14

In [12]:
# Merge with session file
updated_session_file = pd.merge(session_file, all_output_data, on=['Pair', 'Session', 'Sex', 'Cohort'], how='left')
updated_session_file.head(20)

,Session,Cohort,Date,Mouse_x,Pair,Criteria,Sex,Final Outcome_x,Session Outcome_x,DayofHelping,...,FPS,Dimensions,Correlation Image Path,Peak-to-Noise Ratio Path,CNMFE Model Path,Motion Corrected Path,Session Duration,Session Outcome_y,Final Outcome_y,Time Victim Inserted
0,HBTD6,Oct_2021,29.10.2021,847,0847-5839,SSCW,M,H,H,4,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD6/cnmfe_data/corre...,processed-data/Oct_2021/HBTD6/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD6/cnmfe_model/2021...,processed-data/Oct_2021/HBTD6/cnmfe_data/memma...,163.0,H,H,10.0
1,HBTD5,Oct_2021,28.10.2021,847,0847-5839,SSCW,M,H,H,3,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD5/cnmfe_data/corre...,processed-data/Oct_2021/HBTD5/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD5/cnmfe_model/2021...,processed-data/Oct_2021/HBTD5/cnmfe_data/memma...,60.0,H,H,8.0
2,Pool,Oct_2021,31.10.2021,847,0847-5839,SSCW,M,NaN,CTRL,Pool,...,30.0,"(400, 640)",processed-data/Oct_2021/Pool/cnmfe_data/correl...,processed-data/Oct_2021/Pool/cnmfe_data/peak_t...,processed-data/Oct_2021/Pool/cnmfe_model/2021-...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,NaN,NaN,NaN,NaN
3,HBTD2,Oct_2021,24.10.2021,847,0847-5839,SSCW,M,H,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD2/cnmfe_data/corre...,processed-data/Oct_2021/HBTD2/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD2/cnmfe_model/2021...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,527.0,NH,H,4.0
4,Empty,Oct_2021,30.10.2021,847,0847-5839,SSCW,M,NaN,CTRL,Empty,...,30.0,"(400, 640)",processed-data/Oct_2021/Empty/cnmfe_data/corre...,processed-data/Oct_2021/Empty/cnmfe_data/peak_...,processed-data/Oct_2021/Empty/cnmfe_model/2021...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,NaN,NaN,NaN,NaN
5,HBTD4,Oct_2021,27.10.2021,847,0847-5839,SSCW,M,H,H,2,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD4/cnmfe_data/corre...,processed-data/Oct_2021/HBTD4/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD4/cnmfe_model/2021...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,72.0,H,H,7.0
6,Stranger,Oct_2021,02.11.2021,847,0847-5840,SSCW,M,H,NH,Stranger,...,30.0,"(400, 640)",processed-data/Oct_2021/Stranger/cnmfe_data/co...,processed-data/Oct_2021/Stranger/cnmfe_data/pe...,processed-data/Oct_2021/Stranger/cnmfe_model/2...,processed-data/Oct_2021/Stranger/cnmfe_data/me...,502.0,NH,H,12.0
7,HBTD1,Oct_2021,23.10.2021,847,0847-5839,SSCW,M,H,NH,0,...,20.0,"(400, 640)",processed-data/Oct_2021/HBTD1/cnmfe_data/corre...,processed-data/Oct_2021/HBTD1/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD1/cnmfe_model/2021...,processed-data/Oct_2021/Stranger/cnmfe_data/me...,358.0,NH,H,10.0
8,Toy,Oct_2021,01.11.2021,847,0847-5839,SSCW,M,NaN,CTRL,Toy,...,30.0,"(400, 640)",processed-data/Oct_2021/Toy/cnmfe_data/correla...,processed-data/Oct_2021/Toy/cnmfe_data/peak_to...,processed-data/Oct_2021/Toy/cnmfe_model/2021-1...,processed-data/Oct_2021/Stranger/cnmfe_data/me...,NaN,NaN,NaN,NaN
9,HBTD3,Oct_2021,25.10.2021,847,0847-5839,SSCW,M,H,H,1,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD3/cnmfe_data/corre...,processed-data/Oct_2021/HBTD3/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD3/cnmfe_model/2021...,processed-data/Oct_2021/HBTD3/cnmfe_data/memma...,308.0,H,H,16.0
10,HBTD6,Oct_2021,29.10.2021,848,0848-5840,SSCW,M,NH,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD6/cnmfe_data/corre...,processed-data/Oct_2021/HBTD6/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD6/cnmfe_model/2021...,processed-data/Oct_2021/HBTD6/cnmfe_data/memma...,503.0,NH,NH,17.0
11,HBTD5,Oct_2021,28.10.2021,848,0848-5840,SSCW,M,NH,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD5/cnmfe_data/corre...,processed-data/Oct_2021/HBTD5/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD5/cnmfe_model/2021...,processed-data/Oct_2021/HBTD5/cnmfe_data/memma...,515.0,NH,NH,18.0
12,Pool,Oct_2021,31.10.2021,848,0848-5840,SSCW,M,NaN,CTRL,Pool,...,30.0,"(400, 640)",processed-data/Oct_2021/Pool/cnmfe_data/correl...,processed-data/Oct_2021/Pool/cnmfe_data/peak_t...,processed-data/Oct_2021/Pool/cnmfe_model/2021-...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,NaN,NaN,NaN,NaN
13,HBTD2,Oct_2021,24.10.2021,848,0848-5840,SSCW,M,NH,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD2/cnmfe_data/corre...,processed-data/Oct_2021/HBTD2/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD2/cnmfe_model/2021...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,523.0,NH,NH,18.0
14,Empty,Oct_2021,30.10.2021,848,0848-5840,SSCW,M,NaN,CTRL,Empty,...,30.0,"(400, 640)",processed-data/Oct_2021/Empty/cnmfe_data/corre...,processed-data/Oct_2021/Empty/cnmfe_data/peak_...,processed-data/Oct_2021/Empty/cnmfe_model/2021...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,NaN,NaN,NaN,NaN
15,HBTD4,Oct_2021,27.10.2021,848,0848-5840,SSCW,M,NH,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD4/cnmfe_data/corre...,processed-data/Oct_2021/HBTD4/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD4/cnmfe_model/2021...,processed-data/Oct_2021/Pool/cnmfe_data/memmap...,516.0,NH,NH,5.0
16,Stranger,Oct_2021,02.11.2021,848,0848-5841,SSCW,M,NH,VL,Stranger,...,30.0,"(400, 640)",processed-data/Oct_2021/Stranger/cnmfe_data/co...,processed-data/Oct_2021/Stranger/cnmfe_data/pe...,processed-data/Oct_2021/Stranger/cnmfe_model/2...,processed-data/Oct_2021/Stranger/cnmfe_data/me...,62.0,VL,NH,1.0
17,HBTD1,Oct_2021,23.10.2021,848,0848-5840,SSCW,M,NH,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD1/cnmfe_data/corre...,processed-data/Oct_2021/HBTD1/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD1/cnmfe_model/2021...,processed-data/Oct_2021/Stranger/cnmfe_data/me...,488.0,NH,NH,0.0
18,Toy,Oct_2021,01.11.2021,848,0848-5840,SSCW,M,NaN,CTRL,Toy,...,30.0,"(400, 640)",processed-data/Oct_2021/Toy/cnmfe_data/correla...,processed-data/Oct_2021/Toy/cnmfe_data/peak_to...,processed-data/Oct_2021/Toy/cnmfe_model/2021-1...,processed-data/Oct_2021/Stranger/cnmfe_data/me...,NaN,NaN,NaN,NaN
19,HBTD3,Oct_2021,25.10.2021,848,0848-5840,SSCW,M,NH,NH,0,...,30.0,"(400, 640)",processed-data/Oct_2021/HBTD3/cnmfe_data/corre...,processed-data/Oct_2021/HBTD3/cnmfe_data/peak_...,processed-data/Oct_2021/HBTD3/cnmfe_model/2021...,processed-data/Oct_2021/HBTD3/cnmfe_data/memma...,501.0,NH,NH,5.0

In [34]:
# Remove FPS and Dimensions (Miniscope Image)
updated_session_file.drop(columns=['FPS', 'Dimensions'], inplace=True)
updated_session_file.head()

,Session,Mouse,Total Components,Num Accepted,Num Rejected,Correlation Image Path,Peak-to-Noise Ratio Path,CNMFE Model Path,Motion Corrected Path,Session Duration,...,TimeVideoEnd,CaImagingLength(s),Session Outcome_y,DayofHelping,Latency,ReunionDuration,Session length,LatencyMinConverted,AdaNotes,Comments
0,Hab1,8000,113,50,63,processed_data/Jan_2024/Hab1/cnmfe_data/correl...,processed_data/Jan_2024/Hab1/cnmfe_data/peak_t...,processed_data/Jan_2024/Hab1/cnmfe_model/2024-...,processed_data/Jan_2024/Hab1/cnmfe_data/memmap...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HBTD6,8000,153,54,99,processed_data/Jan_2024/HBTD6/cnmfe_data/corre...,processed_data/Jan_2024/HBTD6/cnmfe_data/peak_...,processed_data/Jan_2024/HBTD6/cnmfe_model/2024...,processed_data/Jan_2024/HBTD6/cnmfe_data/memma...,243.0,...,4:03,242.3,H,4,0:52,2:03,2:55,0.87,NaN,NaN
2,RECNvlCtx,8000,413,191,222,processed_data/Jan_2024/NovCtx/cnmfe_data/corr...,processed_data/Jan_2024/NovCtx/cnmfe_data/peak...,processed_data/Jan_2024/NovCtx/cnmfe_model/202...,processed_data/Jan_2024/NovCtx/cnmfe_data/memm...,265.0,...,4:25,264,H,RECNvlCtx,1:11,2:09,3:20,1.18,NaN,NaN
3,HBTD5,8000,157,65,92,processed_data/Jan_2024/HBTD5/cnmfe_data/corre...,processed_data/Jan_2024/HBTD5/cnmfe_data/peak_...,processed_data/Jan_2024/HBTD5/cnmfe_model/2024...,processed_data/Jan_2024/HBTD5/cnmfe_data/memma...,185.0,...,3:05,184.9,H,3,0:16,1:39,1:55,0.27,NaN,NaN
4,Pool,8000,127,36,91,processed_data/Jan_2024/Pool/cnmfe_data/correl...,processed_data/Jan_2024/Pool/cnmfe_data/peak_t...,processed_data/Jan_2024/Pool/cnmfe_model/2024-...,processed_data/Jan_2024/Pool/cnmfe_data/memmap...,NaN,...,NaN,318.8,CTRL,Pool,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# Convert TimeVideoEnd, ReunionDuration, TimeVictimInsertion, TimeOnsetDoorOpening, TimeVictimHeadCrossing, TimeVictimBodyCrossing, Session length to min
updated_session_file['TimeVideoEnd(s)'] = updated_session_file['TimeVideoEnd'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
updated_session_file['ReunionDuration(s)'] = updated_session_file['ReunionDuration'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
updated_session_file['TimeVictimInsertion(s)'] = updated_session_file['TimeVictimInsertion'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
updated_session_file['TimeOnsetDoorOpening(s)'] = updated_session_file['TimeOnsetDoorOpening'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
updated_session_file['TimeVictimHeadCrossing(s)'] = updated_session_file['TimeVictimHeadCrossing'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
updated_session_file['TimeVictimBodyCrossing(s)'] = updated_session_file['TimeVictimBodyCrossing'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)
updated_session_file['Session length(s)'] = updated_session_file['Session length'].apply(lambda x: int(str(x).split(':')[0])*60 + int(str(x).split(':')[1]) if x is not np.nan else np.nan)

# Delete old columns
updated_session_file.drop(columns=['TimeVideoEnd', 'ReunionDuration', 'TimeVictimInsertion', 'TimeOnsetDoorOpening', 'TimeVictimHeadCrossing', 'TimeVictimBodyCrossing', 'Session length'], inplace=True)

In [2]:
session_file = pd.read_csv('data/SESSION_FILE_insilico_2024-11-25_13-03-00.csv')

In [3]:
updated_session_file = session_file
updated_session_file['Normalized components'] = updated_session_file['Num Accepted'] / updated_session_file['Ca Imaging Length(s)']
#print(data.groupby(['Mouse']).head())
# For each unique mouse, sum the normalized components over all days
sum_normalized_components = updated_session_file.groupby(['Mouse'])['Normalized components'].sum()
# Add the sum of normalized components to the data
updated_session_file = updated_session_file.join(sum_normalized_components, on='Mouse', rsuffix='_sum')
# Compute K_id(Num Accepted components for animal i and day d) as k_id (normalized by Session Duration) /sum(k_il over all days) for each animal i and day d
updated_session_file['Normalized components'] = (updated_session_file['Normalized components'] / updated_session_file['Normalized components_sum']) * 100

# Remove the sum of normalized components
updated_session_file = updated_session_file.drop(columns=['Normalized components_sum'])

# Round Ca Imaging Length(s) and Normalized components to 2 decimal places
updated_session_file['Ca Imaging Length(s)'] = updated_session_file['Ca Imaging Length(s)'].round(2)
updated_session_file['Normalized components'] = updated_session_file['Normalized components'].round(2)
updated_session_file.head()

,Excluded,Session,Cohort,Date,Mouse,Pair,Miniscope video,Criteria,Sex,Final Outcome,...,Dimensions,Correlation Image Path,Peak-to-Noise Ratio Path,CNMFE Model Path,Motion Corrected Path,Time Victim Inserted,Maximum Shift,True Number,ManualAnnotationSide,Normalized components
0,False,HBTD1,Oct_2024_synthetic,05.11.2024,1001,1001-0000,05.11.2024_1001,Silicon,M,NH,...,"(400, 640)",processed-data/Oct_2024_synthetic/HBTD6/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD6/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD6/cnmfe_...,/home/aagafono/caiman_data/temp/memmap_10_d1_4...,0,0,102,NaN,17.52
1,False,HBTD2,Oct_2024_synthetic,06.11.2024,1001,1001-0000,06.11.2024_1001,Silicon,M,NH,...,"(400, 640)",processed-data/Oct_2024_synthetic/HBTD5/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD5/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD5/cnmfe_...,/home/aagafono/caiman_data/temp/memmap_09_d1_4...,0,0,102,NaN,16.38
2,False,HBTD3,Oct_2024_synthetic,07.11.2024,1001,1001-0000,07.11.2024_1001,Silicon,M,NH,...,"(400, 640)",processed-data/Oct_2024_synthetic/HBTD2/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD2/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD2/cnmfe_...,/home/aagafono/caiman_data/temp/memmap_06_d1_4...,0,0,102,NaN,16.00
3,False,HBTD4,Oct_2024_synthetic,08.11.2024,1001,1001-0000,08.11.2024_1001,Silicon,M,NH,...,"(400, 640)",processed-data/Oct_2024_synthetic/HBTD4/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD4/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD4/cnmfe_...,/home/aagafono/caiman_data/temp/memmap_08_d1_4...,0,0,102,NaN,17.14
4,False,HBTD5,Oct_2024_synthetic,09.11.2024,1001,1001-0000,09.11.2024_1001,Silicon,M,NH,...,"(400, 640)",processed-data/Oct_2024_synthetic/HBTD1/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD1/cnmfe_...,processed-data/Oct_2024_synthetic/HBTD1/cnmfe_...,/home/aagafono/caiman_data/temp/memmap_05_d1_4...,0,0,102,NaN,17.52

In [5]:
# Save the updated session file
session_file_path = 'data/SESSION_FILE_insilico_2024-11-25_13-03-00.csv'
updated_session_file.to_csv(session_file_path.replace('.csv', '_updated.csv'), index=False)
print(f"Saved updated session file to {session_file_path.replace('.csv', '_updated.csv')}")

Saved updated session file to data/SESSION_FILE_insilico_2024-11-25_13-03-00_updated.csv

In [16]:
# Save updated session file
updated_session_file.to_csv(f'{root}/updated_session_file_MiniscopeCW_all_Moises1.csv', index=False)